" Set the GUI font.
if has('gui_gtk')
  set guifont=FiraCode\ Nerd\ Font\ Mono\ 14,Monospace\ 14
elseif has('gui_win32')
  set guifont=FiraCode\ Nerd\ Font\ Mono:h14,Consolas:h14
endif

" Disable tearoff menus and toolbar.
set guioptions-=t
set guioptions-=T

" vim: fen fdm=marker fmr={{{,}}} fdc=3 et ts=2 sts=2 sw=2
