" Setup path to the configuration directory.
let g:config_dir = expand(has('win32') ?
    \ '$USERPROFILE/vimfiles' :
    \ '~/.vim')

" Configure the <Leader> key.
let g:mapleader = "\<Space>"

" Create an empty autocommand group for configuration files.
augroup vimrc
  autocmd!
augroup end

" Set the default character encoding.
set encoding=utf-8

" Set the number of commands to be remembered in the history.
set history=10000

" Automatically read files that has been changed outside of Vim.
set autoread

" Enable the enhanced command-line completion.
set wildmenu

" Highlight all matches of the search pattern.
set hlsearch

" Jump to matches while typing a search command.
set incsearch

" Show the current command in the bottom right corner.
set showcmd

" Enable automatic indentation of new lines.
set autoindent

" Delete comment characters when joining commented lines.
set formatoptions+=j

" Turn off annoying beeps/flashes on errors.
set belloff=all

" Define escape sequences to change the cursor shape.
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Easy navigation between terminal windows.
tnoremap <C-H> <C-W>h
tnoremap <C-J> <C-W>j
tnoremap <C-K> <C-W>k
tnoremap <C-L> <C-W>l

" Open a new terminal in a horizontal or vertical split.
nnoremap <silent> <Leader>tsp :belowright terminal<CR>
nnoremap <silent> <Leader>tvs :belowright vertical terminal<CR>

" Load common Vim/Neovim settings.
runtime settings.vim

" vim: fen fdm=marker fmr={{{,}}} fdc=3 et ts=2 sts=2 sw=2
